name: Tests

on: [ push, workflow_dispatch ]

jobs:
  run:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "7.4", "8.0", "8.1" ]
    name: PHP ${{ matrix.php-version }}
    steps:
      - name: Install Consul
        run: |
          mkdir -p $HOME/bin \
          && echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_PATH \
          && wget -q "https://releases.hashicorp.com/consul/1.11.1/consul_1.11.1_linux_amd64.zip" \
          && unzip consul_1.11.1_linux_amd64.zip -d $HOME/bin \
          && chmod +x $HOME/bin/consul
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json
          ini-values: precision=14,serialize_precision=-1
      - name: Install Composer deps
        run: composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run tests
        run: ./vendor/bin/phpunit