name: "Tests"

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
  push:
    branches:
      - master
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - '.github/workflows/tests.yaml'

env:
  CONSUL_HTTP_ADDR: "127.0.0.1:8500"

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ["7.4", "8.0", "8.1"]

    name: Tests - PHP ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json
          ini-values: precision=14,serialize_precision=-1
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
      - run: |
          composer update \
            --no-ansi \
            --no-interaction \
            --no-scripts \
            --no-suggest \
            --no-progress \
            --prefer-dist
      - run: |
          wget https://releases.hashicorp.com/consul/1.12.1/consul_1.12.1_linux_amd64.zip
          unzip consul_1.12.1_linux_amd64.zip -d /usr/local/bin/
          rm consul_1.12.1_linux_amd64.zip
          chmod +x /usr/local/bin/consul
          consul --version

      - run: |
          ./vendor/bin/phpunit -c phpunit.xml
